apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: lecture-env
    patch: |-
      - op: add
        path: /data/DJANGO_DEBUG
        value: "false"
      - op: add
        path: /data/DJANGO_ALLOWED_HOSTS
        # TODO: set your stage hostnames
        value: "localhost,127.0.0.1"
      - op: add
        path: /data/DJANGO_CORS_ALLOW_ALL_ORIGINS
        value: "false"
      - op: add
        path: /data/DJANGO_CORS_ALLOWED_ORIGINS
        # TODO: set the browser origin(s) for stage
        value: "http://localhost:3000"
      - op: add
        path: /data/DJANGO_CSRF_TRUSTED_ORIGINS
        value: "http://localhost,http://localhost:3000"
      - op: add
        path: /data/DJANGO_SECURE_PROXY_SSL_HEADER
        value: "false"
      - op: add
        path: /data/DJANGO_SECURE_SSL_REDIRECT
        value: "false"
      - op: add
        path: /data/DJANGO_USE_X_FORWARDED_HOST
        value: "false"
