# Generated by Django 5.2.6 on 2025-09-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='core_messag_session_567bd2_idx',
            old_name='core_mess_session_3e15a5_idx',
        ),
        migrations.AlterField(
            model_name='llm',
            name='base_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
