# Generated by Django 5.2.8 on 2025-11-17 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_mess_session_3e15a5_idx_core_messag_session_567bd2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usecase_type', models.CharField(choices=[('BASIC_CHAT', 'Basic Chat'), ('RAG_CHAT', 'RAG Chat'), ('CUSTOM', 'Custom')], max_length=20)),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('tools', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='core.llm')),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.agent'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['usecase_type', 'is_active'], name='core_agent_usecase_d7cf8b_idx'),
        ),
    ]
