# Generated by Django 5.2.8 on 2025-11-17 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agent_chatsession_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasources', to='core.llm')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='core_dataso_is_acti_aef0dd_idx')],
            },
        ),
    ]
